#!/usr/bin/env bash
# Script that installs and configures HAproxy load balancer on my lb-01 server

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get -y install haproxy=2.5.\*
sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg

echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 1507-web-01 34.73.223.152:80 check\n\tserver 1507-web-02 35.185.90.215:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restarit